warmup_epochs: 2
init_lr: 1e-4
max_lr: 1e-3
final_lr: 1e-4
aggregate_over_edges: false
model_name: enzyme_reaction_clip
chemprop_num_layers: 5
chemprop_hidden_dim: 1280
chemprop_node_dim: 9
chemprop_edge_dim: 3
chemprop_pool: null

# NOTE: If provided, overrides all args passed to model.
# NOTE: use '_' instead of '=' in the filename
# Note: this is just the fn, e.g., epoch_0-step_62.ckpt
ckpt_fn: null