defaults:
  - filepaths: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - override hydra/launcher: quest_cpu
  - _self_

similarity_score: rcmcs
dataset: sprhea
toc: v3_folded_v3_pt_ns
cutoffs: [80, 60, 40]
blosum_ub: 5e2
blosum_lb: -2e3

hydra:
  run:
    dir: ${filepaths.clustering}