defaults:
  - filepaths: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - override hydra/launcher: quest_cpu
  - _self_

similarity_score: esm
dataset: sprhea
toc: v3_folded_n_100
cutoffs: [99, 98, 97, 96, 95]
blosum_ub: 5e2
blosum_lb: -2e3

hydra:
  run:
    dir: ${filepaths.clustering}