defaults:
  - filepaths: base
  - override hydra/launcher: quest_cpu
  - _self_

dataset: sprhea
toc: v3_folded_pt_ns
rules: ${filepaths.artifacts}/minimal1224_all_uniprot.tsv

hydra:
  run:
    dir: ${filepaths.data}/${...dataset}
  job:
    chdir: True